### ISSUE TITLE
A problem with very long tables first row gets repeated on the second page

### ISSUE THREAD

**Issue by ouboub** [kjambunathan/org-mode-ox-odt#103]
hi 

I attach an example of an org file and its corresponding exported odt version
the table in question start with with a row that is followed by a lot of other cells (containing a sort of checkboxes but this is not the point), the table is very long and continues on the second page, however the first row of the table is repeated on the second page, which is not what I want.
Do I miss here something? Is this by design or a bug, if it by design: any way to turn this behavior off?
[long-table.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/7272223/long-table.zip)

**Comment by kjambunathan** [comment]
> ... however the first row of the table is repeated on the second page, 

When there are more than one rowgroups, cells in first rowgroup  are considered header cells.   When you really have a big excel file--think of a data frame with huge number of rows in Rstats etc--you really want to see the headers when you are grokking 1000th or 10,000th row in the table.

To achieve what you want delete all hlines from the table.  

i.e., instead of this pattern ad-infinitum

```
#+ATTR_ODT: :list-table t
- | /    | /     | /    | /    | /    |
- | <l8> | <l14> | <l8> | <l8> | <l8> |
- 
- ----------------  
  - *General remarks?* 
  - More text
  - 
  - 
  - 
- ----------------
  - 
  - Text
  - ☒ Text
  - □ Text
  - □ More text
- ----------------
  - 
  - Text
  - ☒ Text
  - □ Text
  - □ More text
- ----------------
  - 
  - Text
  - ☒ Text
  - □ Text
  - □ More text

```
you want this pattern ad-infinitum

```
#+ATTR_ODT: :list-table t
- | /    | /     | /    | /    | /    |
- | <l8> | <l14> | <l8> | <l8> | <l8> |
- 
-   
  - *General remarks?* 
  - More text
  - 
  - 
  - 
- 
  - 
  - Text
  - ☒ Text
  - □ Text
  - □ More text
- 
  - 
  - Text
  - ☒ Text
  - □ Text
  - □ More text
- 
  - 
  - Text
  - ☒ Text
  - □ Text
  - □ More text
```

**Comment by ouboub** [comment]
thanks, a lot, that solves it!
