### ISSUE TITLE
Add support for relative column widths in tables with spanned cells

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#107]
**Add support for relative column widths in tables with spanned cells**

Cc. @ouboub 

```
Width cookies work here

#+ATTR_ODT: :style "GriddedTable"
| <l10> | <l20> |
| a     | b     |
| c     | d     |

but not here.

#+ATTR_ODT: :style "GriddedTable"
#+ATTR_ODT: :span "@1$2{2:1}"
| <l10> | <l20> |
| a     | b     |
| c     | d     |

Also the second table has more than 2 columns.
```

**Comment by QiangF** [comment]
I find the widths keywords may introduce some confusion:
1. the width specification in horizontal rules "<l10>" has no effect after this change
2. the horizontal rules "<l10>" sits right above the column, it's more straightforward than the ":widths" keyword, I mean you don't to look up in order to find the column width, why not just use the number in the horizontal rules, and it should just add up for a column span.
