### ISSUE TITLE
Empty space removed when org-odt-prettify-xml  is set to t

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#148]
I have added a space in the num-suffix of OrgNumberedList:

    <text:list-style style:name="OrgNumberedList">
    <text:list-level-style-number text:level="1"
                                    style:num-prefix="("
                                    style:num-suffix=") "
                                    style:num-format="1">
        <style:list-level-properties text:space-before="0.4cm"
                                    text:min-label-width="0.0cm"/>
    </text:list-level-style-number>
    </text:list-style>

When org-odt-prettify-xml is t, that space is removed, try export a numbered list:  

    1. hello
    2. world

Just set org-odt-prettify-xml to nil is fine.

**Comment by kjambunathan** [comment]
> Empty space removed when `org-odt-prettify-xml` is set to t

Fixed in https://github.com/kjambunathan/org-mode-ox-odt/commit/0ab33186b4c1b28f98dffa6cd917eb23989e22b5

The intention of this variable is to get the sense of the tree structure of XML file.  As the docstring says it is NOT for production use.  That said, if something is achievable with `tidy`, I willl definitely consider it.

-----

`org-odt-prettify-xml` is a variable defined in `ox-odt.el`.

Its value is nil

Specify whether or not the xml output should be prettified.

When this option is turned on, use
`org-odt-prettify-xml-buffer` (i.e., specifically HTML tidy) on
component xml buffers before they are saved.  Since this function
creates line breaks, it may introduce extraneous and undesirable
whitespace in exported document.  So, don’t use this option in
production.  Use this for developing ODT-specific features or to
make sense of OpenDocument XML produced by a third party, say
LibreOffice.
