### ISSUE TITLE
error enabling org-mode-ox-odt instead of default odt

### ISSUE THREAD

**Issue by qkweint** [kjambunathan/org-mode-ox-odt#186]
after checking whether emacs uses the built-in version instead of this repository's version, I have found that I need to enable this repository's version. However enabling it causes and error.

This code snippet is taken straight from the README of this repo

 ```
(progn
    (require 'package)
    (setq load-path
      (cons
       (package-desc-dir (package--get-activatable-pkg 'ox-odt))
       load-path))
    (load-library "ox-odt")) 
```

 results in a `wrong type argument: pacakge-desc, nil` error

**Comment by kjambunathan** [comment]
I am not on my desktop ...

I looked at your dotemacs and my guess is you aren't enabling packages at
startup.

So try adding

(package-activate 'ox-odt)

after

(require 'package)

and eval the snippet once again (or restart emacs)


Instead of

 (package-activate 'ox-odt)

you can also do

(package-activate-all)

If either of these things doesn't work.  Let me know.  I will dig deeper
into pacakge.el.


My guess is there might be a simpler solution based on adding 'ox-odt to
package-load-list

Let me know.what you find

If it works, tell me what works. I will update the README accordingly

**Comment by qkweint** [comment]
> If either of these things doesn't work.  Let me know.  I will dig deeper
into pacakge.el.

I use straight.el and not package.el so this doesn't really apply

**Comment by kjambunathan** [comment]
For straight.el, try the suggestion here
https://github.com/kjambunathan/org-mode-ox-odt/discussions/133

Skip the files that have jabref in name.

That discussion has more notes.

The easiest thing to do for testing purposes is to just visit the file, and
load it with 'load-file'.   This is precisely what my recipe does, but
after accounting for path changes due to version changes

**Comment by kjambunathan** [comment]
See https://github.com/kjambunathan/org-mode-ox-odt#if-you-have-lost-all-hope-of-using-this-exporter-
