### ISSUE TITLE
org-->ods exporter, problem with two dates in one cell

### ISSUE THREAD

**Issue by ouboub** [kjambunathan/org-mode-ox-odt#214]
Hi

I would like to export the following table to ods
```
#+Name: Test-Date
|  Nr | Document1                       | Summary                   | Autor | Response     |
|-----+---------------------------------+---------------------------+-------+--------------|
| 653 | <2022-07-12> =and= <2022-08-29> | =Resolved:=  <2022-08-25> | Me    | <2022-07-14> |
```
however whatever I do in the cell with the 2 dates, the export function does not export the date, I attach the result.

[Bug-date.zip](https://github.com/kjambunathan/org-mode-ox-odt/files/9926669/Bug-date.zip)

**Comment by kjambunathan** [comment]
If I export with following settings 

```lisp
(custom-set-variables
 '(org-display-custom-times t)
 '(org-time-stamp-custom-formats '("<%d/%m/%Y>" . "<%d/%m/%Y %I:%M %p>"))
 '(org-odt-use-date-fields t))
```

I get 

![Screenshot from 2022-11-04 08-49-14](https://user-images.githubusercontent.com/19869864/199877885-418d92d2-c26b-421d-8744-907a2aa3d5f6.png)

which seems OK to me.

If you want the timestamp delimiters, then  you have to modify the [`org-odt-timestamp`](https://github.com/kjambunathan/org-mode-ox-odt/blob/odtxml/lisp/ox-odt.el#L8591) to remove the `[]` and `<>` delimiters. 

I have retained the timestamp delimiters in the output because that is what the LaTeX and HTML exporters do.    That is ...  the delimiters are there to have some uniformity in the exported output across all backends.   I believe there is no strong opinion on if the delimiters have to be stripped or retained in the output.  

So, if you could convince the `org` developers to strip the delimiters---`[]` and `<>`---timestamp in LaTeX and HTML, I will follow through.

Otherwise, use the following 

```lisp
(defun org-odt-timestamp (timestamp contents info)
  "Transcode a TIMESTAMP object from Org to ODT.
CONTENTS is nil.  INFO is a plist used as a communication
channel."
  (let* ((_raw-value (org-element-property :raw-value timestamp))
	 (type (org-element-property :type timestamp)))
    (if (not (plist-get info :odt-use-date-fields))
	(let ((value (org-odt-plain-text
		      (org-timestamp-translate timestamp) info)))
	  (cl-case (org-element-property :type timestamp)
	    ((active active-range)
	     (format "<text:span text:style-name=\"%s\">%s</text:span>"
		     "OrgActiveTimestamp" value))
	    ((inactive inactive-range)
	     (format "<text:span text:style-name=\"%s\">%s</text:span>"
		     "OrgInactiveTimestamp" value))
	    (otherwise value)))
      (cl-case type
	(active
	 (format "<text:span text:style-name=\"%s\">%s</text:span>"
		 "OrgActiveTimestamp"
		 (format "%s" (org-odt--format-timestamp timestamp))))
	(inactive
	 (format "<text:span text:style-name=\"%s\">%s</text:span>"
		 "OrgInactiveTimestamp"
		 (format "%s" (org-odt--format-timestamp timestamp))))
	(active-range
	 (format "<text:span text:style-name=\"%s\">%s</text:span>"
		 "OrgActiveTimestamp"
		 (format "%s&#x2013;%s"
			 (org-odt--format-timestamp timestamp)
			 (org-odt--format-timestamp timestamp 'end))))
	(inactive-range
	 (format "<text:span text:style-name=\"%s\">%s</text:span>"
		 "OrgInactiveTimestamp"
		 (format "%s&#x2013;%s"
			 (org-odt--format-timestamp timestamp)
			 (org-odt--format-timestamp timestamp 'end))))
	(otherwise
	 (format "<text:span text:style-name=\"%s\">%s</text:span>"
		 "OrgDiaryTimestamp"
		 (org-odt-plain-text (org-timestamp-translate timestamp)
				     info)))))))

````

**Comment by ouboub** [comment]
Thanks the function **org-odt-timestamp** solved my problem.
Ihor Radchenkor started to consider modifying the stamp format, because it already has caused some problems
if you change a TODO to DONE, the timestamp in some occasions ended up strange.
Not many people answered so far to the proposal......
thanks again
