### ISSUE TITLE
ODT_STYLES_FILE doesn't respect Htmlfontify style settings

### ISSUE THREAD

**Issue by camio** [kjambunathan/org-mode-ox-odt#215]
A, albeit terrible, workaround is to comment out the `(insert "\n<!-- Org Htmlfontify Styles -->\n"...` expression in `ox-odt.el` which otherwise overrides what's in the specified `ODT_STYLES_FILE`.

**Comment by kjambunathan** [comment]
Yes, I think the ODT generated Htmlfontify styles could be moved ahead.   

(I will merge your PR after some time)

There is a custom variable `org-odt-create-custom-styles-for-srcblocks` which does precisely that; that is, "not create duplicate styles".  I agree that this variable is a "legay" one, and could be removed.  

In order to understand why things are this way, one needs to see it in historical context ....

Fontification of src blocks in exported documents  forced me to create styles on the fly--that is styles that are over and above  those in `styles.xml`-- in first place.  This "create styles on the fly" is almost a decade old,  and dates back to initial days of the ODT exporter, when my understanding of the ODT spec./LibreOffice was less than nuanced.  

That is ... "extra styles for src blocks" has it origins much before I allowed the user or  the odt exporter to create arbitrary styes on the fly.  I started allowing "arbitrary styles on the fly" after discovering LibreOffice's lax lenient behaviour wrt muliply defined styles and using it to my advantage.

So, the appropriate thing to do would be to remove the  `org-odt-create-custom-styles-for-srcblocks` , and have the Htmlfontify styles moved ahead.

**Comment by kjambunathan** [comment]
> ODT_STYLES_FILE doesn't respect Htmlfontify style setting

The feature you are suggesting is already there.  You can see demo at [How do I fontify src blocks with a theme different from the one I am using?](https://github.com/kjambunathan/org-mode-ox-odt/issues/60).

What you are trying to accomplish, and what is documented in the above issue are just the same.  Same things; but expressed differently.

**Comment by QiangF** [comment]
I think the fix is good for ordinary users without looking into the source code, "ODT_STYLES_FILE" is an user option, it should have hider precedence. Faulty document or not really doesn't matter much.

**Comment by kjambunathan** [comment]
This bug is superceded by [Ensure that the styles.xml doesn't ever contain duplicate styles](https://github.com/kjambunathan/org-mode-ox-odt/issues/220). See [this comment](https://github.com/kjambunathan/org-mode-ox-odt/pull/216#issuecomment-1330363447) for more details.
