### ISSUE TITLE
How to set the frame of a figure to be aligned "as-char" and get centered?

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#27]
In LibreOffice figure placements are unpredictable, if the align type is 'paragraph', if the align type is "as-char", the frame is not centered, how can I get both?

**Comment by QiangF** [comment]
I have to manually change the achor type of "OrgImageCaptionFrame" in the
style.xml file with text:anchor-type="as-char".
Though there is a style nameed CaptionedAs-CharImage in the frame-cfg-alist:

    ("CaptionedAs-CharImage"
        ("OrgCaptionedImage"
        " style:rel-width=\"100%\" style:rel-height=\"scale\"" "as-char")
        ("OrgInlineImage" nil "as-char"))

I guess it has the frame set as-char, But the following image frame's achor-tyoe
is still paragraph.  

    #+caption: CaptionedAs-CharImage
    #+attr_odt: :width 7 :style "CaptionedAs-CharImage" 
    [[file_path]]

**Comment by kjambunathan** [comment]
> I have to manually change the achor type of "OrgImageCaptionFrame" in the
style.xml file with text:anchor-type="as-char".

    #+attr_odt: :width 7 :anchor "as-char" 
    [[./org-mode-unicorn.png]]

------


I have problems understanding what you are trying to achieve.  

Share a screenshot that  has the_undesirable_ outcome and tell me what aspects you want _repaired_.  You can also share  your desired output looks like.  This way both of us would have the _same_ idea of desired outcome.

------

That said, I understand that you are working with documents that have lots of images with captions.  The problem with such documents is that:

1. images would get positioned at "random" places throughout the document i.e., sometimes that images would be placed at the beginning of the page, sometimes at the end, sometimes at the lower half etc.  

2. Some pages of the document will appear to have _large_ whitespaces at the end of the page.  This is because the relative order of the image and paragraphs surrounding it is just the same as in org document.

To get a better handle on what is happening, in LibreOffice GUI, I suggest that you

1. Turn  on `View->Text Boundaries`
2. With the desired frame selected, bring up the navigator by pressing `F11` and see what frame styles are used.

If you do (1) and (2) you would realize that a captioned image has two frames: the inner frame uses the style `OrgCaptionedImage` and the outer frame uses `OrgImageCaptionFrame`.

You may also want to experiment with 

1. `Format->Frame and Object->Properties->Wrap`
1. `Format->Frame and Object->Type->Position`

I understand that the above pointers are too generic to be of immediate help to you.  This is because how the document gets laid out depend on the relative sizes of the paragraphs and images in _your_document.  So, if I have access to a sample `org` and `odt` document that manifests the problem you are facing, and some pointers on of how you imagine your final document, I would be able to help you better.

**Comment by QiangF** [comment]
Thank you Sir. It's clear that the issue is how to make OrgImageCaptionFrame
(the outer framed) centered no matter what the anchor type for it is.

**Comment by QiangF** [comment]
An example would be 

    #+caption: org mode unicorn
    #+label: 1
    #+attr_odt: :width 7 :anchor "as-char" 
    [[./org-mode-unicorn.png]]

    #+caption: org mode unicorn
    #+label: 2
    #+attr_odt: :width 7 :anchor "paragraph" 
    [[./org-mode-unicorn.png]]

In the example figure 1 is left aligned, figure 2 is ceter aligned, how can you
change figure 1 to center aligned?

**Comment by QiangF** [comment]
The drifting of images or frames whose anchor type is not as-char is a known
libreoffice issue, the image drifting would cause images to be totally out of
order when there are many images.

see https://ask.libreoffice.org/en/question/10022/picture-placement-issues/

**Comment by kjambunathan** [comment]
> how can you change figure 1 to center aligned?

Surround it with a center block.

    #+BEGIN_CENTER
    #+caption: org mode unicorn
    #+label: 1
    #+attr_odt: :width 7 :anchor "as-char" 
    [[./org-mode-unicorn.png]]
    #+END_CENTER
