### ISSUE TITLE
Feature request: preview current level

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#30]
For a long document, a full export will take time and is unnecessary during the
editing, some latex mode has preview functionality. Borrow that idea and define
a preamble structure, concatenate the preamble and the current level into a temp
file, export that file and use docview to view the result.

    #+begin_preamble
    #+title: title
    #+odt_styles_file: "./text_template.ott"
    #+options: toc:nil author:nil tex:t latex:t :H 6
    #+language: en
    #+bibliography_file: ./my_bib.bib
    #+end_preamble

**Comment by kjambunathan** [comment]
> ... some latex mode has preview functionality.

Could you be a bit more _specific_.  Which _specific_ latex package are you referring to? This will help me add the preview functionality.

**Comment by kjambunathan** [comment]
#### Pre-requisites

Ensure that you are able to export an `org` file to `odt` `asynchronously'. i.e., The  following keysequence `C-c C-e C-a C-o C-o` should generate the `odt` file just fine.  

![screenshot from 2017-10-27 18-26-03](https://user-images.githubusercontent.com/19869864/32105008-88324ce2-bb44-11e7-82a7-b71d6fcd1805.png)

#### Add some file local variables to your `org` file

```
# Local Variables:
# org-odt-preferred-output-format: "pdf"
# after-save-hook: (lambda nil (org-odt-export-to-odt 'async))
# End:
```

1. Add the above snippet towards _*the end*_ of the `org` file.
2. Save and revert the file i.e., `C-x C-s`.  `C-x C-v` so that the above local variables take effect.
3. Export the file.

#### Open the PDF file in another window

1. Open the `PDF` file in `doc-view-mode` i.e. `C-x C-f  test-new.pdf`
1. Fit page to window i.e., `H`
2. Turn on Auto Revert i.e., M-x auto-revert-mode
3. Goto a page that is of interest to you i.e., `M-g M-g`

#### Arrange the `org` and `pdf` windows side-by-side

You should be seeing something like this. 

![screenshot from 2017-10-27 18-21-50](https://user-images.githubusercontent.com/19869864/32105512-61492fcc-bb46-11e7-9310-717496e4c9aa.png)

#### Modify `org` file and `save` it

1. Modify `org` file and `save` it
2. Wait for sometime.
3. You will see that window displaying the `pdf`file refresh itself.

**Comment by kjambunathan** [comment]
> For a long document, a full export will take time and is unnecessary during the
editing,

You don't have to export _the whole_ file.  You can export just a subtree `C-c C-e C-s o o` or only the visible portions `C-c C-e C-v o o`

**Comment by QiangF** [comment]
"Export just a subtree" has problems in finding the references, as the
bibliography definition is at the end of the document, otherwise it is just
what I want.

Export subtree seems to be aware of the style file specification in the
beginning, so I would suggest add a bibliography file path specification at the
beginning of the document, like:

    #+bib_file: ./my_bib.bib

Then insert bibliography with:

    #+bibliography: local

Add a local specification if the user want one bibliography for each Chapter?

**Comment by QiangF** [comment]
The latex preview mode I mentioned is part of auctex, but I think we don't need
that anymore. Another fancy functionality of auctex is when you click in the
exported document, it can jump to the source of the part where you clicked,
since org mode files are much readable than tex file, we don't need that either.
https://www.gnu.org/software/auctex/manual/preview-latex.html
