### ISSUE TITLE
Table caption positioned below table

### ISSUE THREAD

**Issue by QiangF** [kjambunathan/org-mode-ox-odt#55]
This happens to ox-odt-9.2.1.205. The table caption should be above the table.

**Comment by kjambunathan** [comment]
> This happens to ox-odt-9.2.1.205. The table caption should be above the table.

You need to customize the variable `org-odt-caption-and-xref-settings`.   You can not only customize how the caption is formatted, you can also how the cross references are generated.  You can do this for images, tables, src listings etc.

See the screenshot below for details.

![Screenshot from 2019-03-15 18-19-18](https://user-images.githubusercontent.com/19869864/54432408-2594ad80-474f-11e9-9ebe-d70b8657c10c.png)

**Comment by QiangF** [comment]
Thank you!

**Comment by QiangF** [comment]
Perhaps we should have a better default, the default value for caption position for table should be above.

    (:TABLE: :caption-position above
            :caption-format (category " " counter ": " caption)
            :xref-format (value))

and the math formula should have no caption, currently even without a caption there are extra spaces below a formula.

    (:MATH-FORMULA: :caption-position nil
                    :xref-format (text)
                    :label-format ("(" counter ")"))

**Comment by kjambunathan** [comment]
>  the default value for caption position for table should be above.

Done.

> currently equation with label but without a caption there are extra spaces below a formula.

Thanks for including the `Org` snippet.  The snippets is very helpful in understanding the specific issue
 you are describing.  

I acknowledge the problem.  I will look in to it.

**Comment by QiangF** [comment]
I think I've found the cause for the extra empty caption line: org-odt--render-image/formula should parse the returned string of org-odt-format-label to see if the caption content is nil.

**Comment by kjambunathan** [comment]
> I think I've found the cause for the extra empty caption line: org-odt--render-image/formula should parse the returned string of org-odt-format-label to see if the caption content is nil.

Thanks for taking time to look at the source code.    The caption text may be empty, but since has a label it could be referenced later.  So, I need to sneak in a bookmark there. 

So, even if the LibreOffice output makes you think that there is _no_ caption in the output, there is actually a bookmark there.   Now, I have slightly re-arranged things so that the exporter does the right thing.

 There is a comment in `ox-odt.el` which pretty much says it.

```
;; Sneak in a bookmark.  The bookmark is used when the
 ;; labeled element is referenced with a link that
 ;; provides its own description.
```

It will be easier for you to understand the above comment if you export the test case (see the commit message) with and without the fix.  Pay particular attention to where cross-reference figures and formulas using links that has a description.
