### ISSUE TITLE
Documenting this module?

### ISSUE THREAD

**Issue by apiraino** [kjambunathan/org-mode-ox-odt#64]
Hello!

I've randomly found this module, looks interesting!

Would it be possible to give a brief overview of the features compared to the stock ODT export module (I usually export to ODT from org-mode)? That would really useful :-)

thanks

**Comment by QiangF** [comment]
This package is made by the original author of the org odt exporter. It's support more types of odt element, such as list in table, subfigure, multiple column section, bibliographical citations and much more. You can see examples in the samples folder.

**Comment by apiraino** [comment]
Hi @QiangF thanks for the reply.

I think you're referring to the [testing/examples](https://github.com/kjambunathan/org-mode-ox-odt/tree/master/testing/examples) directory, I'll have a look there.

thanks!

**Comment by kjambunathan** [comment]
> Would it be possible to give a brief overview of the features compared to the stock ODT export module

This is a fair request.  I have accumulated fair amount of fixes since the fork.  Documenting it in a formal way take substantial effort, and I wanted to postpone this work until someone actually requested for it.  Now that you have made a request, I will update the manual to reflect the current state-of-affairs.  

_(I am hopeful of getting  the first version out in a week or two.)_

For now, I have uploaded _a very old manual_ to the repository.  You can access it at https://kjambunathan.github.io/org-mode-ox-odt/

> I think you're referring to the [testing/examples](https://github.com/kjambunathan/org-mode-ox-odt/tree/master/testing/examples) directory, I'll have a look there.

It is sufficient if you look at the `odt/ ` subdir of that dir i.e., https://github.com/kjambunathan/org-mode-ox-odt/tree/master/testing/examples/odt.  This directory in the git repo is bundled as `samples/` subdir of as part of `ox-odt-*.tar` ELPA tar at https://github.com/kjambunathan/kjambunathan.github.io/tree/master/elpa i.e., If you followed instructions in https://github.com/kjambunathan/org-mode-ox-odt/blob/master/README.md and installed ODT exporter via the package manager, the sample files are automatically available  in your `.emacs.d/`.

Instead of writing a one or two words or paragraph about new features, I would rather prefer to flesh out all the details once-and-for-all-time.  Till then you have two options

1. Look at the closed issues for specific help on a feature.
2. Look at the git commit logs.
3. Look at the source code.

You will find that my notes and commit logs are sufficiently elaborate and helpful.

**Comment by apiraino** [comment]
wow @kjambunathan thank you so much for this detailed answer, really appreciated! :+1: 
I'll follow your instructions and also keep an eye on this repo for being notified about additions.

Thank you so much!

**Comment by apiraino** [comment]
I think this issue can now be closed.

Thanks!
