### ISSUE TITLE
handle smart single quotation marks

### ISSUE THREAD

**Issue by mooseyboots** [kjambunathan/org-mode-ox-odt#88]
when i export text that uses single quotation marks for either direct speech or for scare quotes around single terms, they appear as apostrophes (ie curling to the left), meaning that after export a single opening quote appears like a single closing one. whereas when single quotes are used as nested quotes inside double quotes, they export correctly. would it be possible to handle single quotation marks like double ones? non-US english speakers tend to use them.

**Comment by kjambunathan** [comment]
> when i export text that uses single quotation marks for either direct speech or for scare quotes around single terms, they appear as apostrophes (ie curling to the left), meaning that after export a single opening quote appears like a single closing one. whereas when single quotes are used as nested quotes inside double quotes, they export correctly. would it be possible to handle single quotation marks like double ones? non-US english speakers tend to use them.

Handling of quotes is done by the Org export engine, and NOT by ODT exporter.

There is a custom setting for smart quotes.  See https://github.com/kjambunathan/org-mode-ox-odt/blob/f022150f3a046511dba18a509de621ec35daf075/lisp/ox.el#L633. 

What gets replaced with what is documented here. https://github.com/kjambunathan/org-mode-ox-odt/blob/f022150f3a046511dba18a509de621ec35daf075/lisp/ox.el#L5448

What language are you using?   Can you give the unicode value or names of the actual output you want.  An example desired output will be good.

FWIW, ODT exporter uses the entry corresponding to `:utf-8' in that dictionary of translations.  If you find something missing, I will be happy to add one or you can add one locally.

**Comment by mooseyboots** [comment]
Hi again,

I'm trying just with English for starters.

`org-export-with-smart-quotes' is set to t.

If i write some thing like 

```A simple test 'example'.``` in org (using no other quotation marks), it exports as ```A simple test [:utf-8 "’"]example[:utf-8 "’"].``` That is, it uses what the dictionary-alist calls 'secondary-closing' both before and after the word "example". What i think it should do is use 'secondary-opening' before the word "example". 

As it stands i have to use " " throughout my org file in order for it to export correctly (forcing it to use primary-opening and primary-closing), so using secondary (single) quotes is not possible.

Hopefully that is at least enough information for you to know what I mean.

**Comment by mooseyboots** [comment]
Hi again,

I just tried the same example with a latex export and the problem is also present in that case, so perhaps this is not really your responsibility. But as I mainly export to odt (and you know how everything works) I just asked here by default.

**Comment by kjambunathan** [comment]
> `A simple test 'example'.` in org (using no other quotation marks), it exports as `A simple test [:utf-8 "’"]example[:utf-8 "’"].` That is, it uses what the dictionary-alist calls 'secondary-closing' both before and after the word "example". What i think it should do is use 'secondary-opening' before the word "example".
> 
> As it stands i have to use " " throughout my org file in order for it to export correctly (forcing it to use primary-opening and primary-closing), so using secondary (single) quotes is not possible.

The request you are making has appeared in the Orgmode mailing list in the past.  And in all instances, the request has been shot down by Nicolas Goaziou, for lack of very strong arguments.  

I am citing the threads, and quoting the relevant parts.  This is just so that you can anticipate what arguments will be thrown at you, and be prepared to defend your request.


1. [[O] Bug: Secondary smart quotes are exported as apostrophes. [9.1.14 (9.](https://lists.gnu.org/archive/html/emacs-orgmode/2019-01/msg00000.html)

> > According to documentation (org-export-with-smart-quotes) should treat
> "pairs of single quotes as secondary quotes." This text:

> Only within primary quotes! If there are no primary quotes around, you
don't need a second level of quotation, and single quotes are not
special.

-------

> When you need that level of precision, smart quotes are not for you.
"Smart" quotes are a dumb way to automate some basic typographic rules.

-----


> I think you are mixing up the level of quotation and the glyph used. You
can export "..." as single quotes by setting
`org-export-smart-quotes-alist' accordingly.

-----

> I think cryptic (?) double quotes are perfectly fine since you can
export them as single quotes in the end.

-----

> that current system does not use "double
quotes" and "single quotes", but "primary quotes" and "secondary
quotes". This is an important distinction, as it is more general: some
languages do not use, e.g., single quotes at all. It just happens that
Org uses double quotes as primary quotes, but only as a class of
characters, not as a literal symbol. As a consequence, as odd as it may
sound, I would consider it a regression if Org exported " as double
quotes and ' as single quotes exclusively.



2.  [Re: Smart quotes not working correctly with single quotes](https://lists.gnu.org/archive/html/emacs-orgmode/2021-05/msg01178.html)

> I confirm single quotes are only recognized
as second level quotes, i.e., nested within double quotes, or as
apostrophes.

3. [Re: [O] Bug: Exporting smart single quotes in Org 8.3 seems broken [8.3.](https://lists.gnu.org/archive/html/emacs-orgmode/2015-10/msg00123.html)

>  `org-export-smart-quotes-alist' aims to be
typographically correct for all handled languages, so it is not
customizable.


------------


As an onlooker, who spent hardly a few minutes understanding the issue, this is my current understanding:

1.  The double quote char is a markup element for "outer quote" i.e., it is wrong to assume that if you type double quote in your text, it will appear as double quote in the output.  This is much similar to how you view the '*', '/' markup chars.  They don't appear as such in the output, but control how the text is styled.

2.  The single quote char is a markup for "inner quote" ONLY IF it occurs within the double quote markup char.  When the single quote occurs in a text NOT SURROUNDED by "double quote" it is just an apostrophe.

3. If you are not happy with Org mode markup, use `org-entities` or better just the type characters themselves.

4.  My gut feeling--it is only a gut feeling--the single quote is overloaded.  It has multiple interpretations depending on the context.  Sometimes it is just an apostrophe, other times it is a quote.  I believe rules 1-3 helps with apostrophes in a graceful way.   i.e., if the rules 1-3 are changed, then there will be lots of complaints about apostrophes and single quotes.

I understand what your concern is.  You concern seems to be  "In my Org buffer, I see a single quote.  In the exported document I want to see a stylish single quotes.  When I need single quotes in the output, why should I be typing double quotes in the Org buffer.  I can't squint my brain so much".   I also feel likewise.

I think the simplest of solution would be for use to just type out the curved quotes the way you want in the Org buffer.  This way you don't have to contort the Orgmode as a markup dictates.  Take a look at some of these packages  https://www.emacswiki.org/emacs/TypographicalPunctuationMarks.  They could be of help.

As I said, this issue of smart quotes is something that you have to find a solution for on your own or after discussing it with Org mode maintainers.

**Comment by kjambunathan** [comment]
> Take a look at `C-x 8 C-h` 

```
C-x 8 {		“
C-x 8 |		¦
C-x 8 }		”
```

```
C-x 8 [		‘
C-x 8 ]		’

```

The `C-x 8` bindings are also available as `A-` bindings.   And if you have electric pair turned on, 

```
(defcustom electric-quote-chars '(?‘ ?’ ?“ ?”)
  "Curved quote characters for `electric-quote-mode'.
This list's members correspond to left single quote, right single
quote, left double quote, and right double quote, respectively."
  :version "26.1"
  :type '(list character character character character)
  :safe #'(lambda (x)
	    (pcase x
	      (`(,(pred characterp) ,(pred characterp)
		 ,(pred characterp) ,(pred characterp))
	       t)))
  :group 'electricity)
```

then typing `A-[` gives me ‘’, and `A-S-[` gives me “”.

If you have no use for any of these characters,

```

```
C-x 8 " SPC	"
C-x 8 " "	¨
C-x 8 " A	Ä
C-x 8 " E	Ë
C-x 8 " I	Ï
C-x 8 " O	Ö
C-x 8 " U	Ü
C-x 8 " a	ä
C-x 8 " e	ë
C-x 8 " i	ï
C-x 8 " o	ö
C-x 8 " s	ß
C-x 8 " u	ü
C-x 8 " y	ÿ
```

```
C-x 8 ' SPC	'
C-x 8 ' '	´
C-x 8 ' A	Á
C-x 8 ' E	É
C-x 8 ' I	Í
C-x 8 ' O	Ó
C-x 8 ' U	Ú
C-x 8 ' Y	Ý
C-x 8 ' a	á
C-x 8 ' e	é
C-x 8 ' i	í
C-x 8 ' o	ó
C-x 8 ' u	ú
C-x 8 ' y	ý
```

then you can remove prefix bindings for `C-x 8 "` and `C-x 8 '` and have `C-x 8 "` and `C-x 8 `` type the fancy quotes themselves.

This way you don't have to rely on other packages to do your work.

**Comment by kjambunathan** [comment]
>  remove prefix bindings for C-x 8 " and C-x 8 ' and have C-x 8 " and C-x 8 ` type the fancy quotes themselves.

This seems to work

```
(custom-set-variables
 '(electric-pair-mode t))

(with-eval-after-load 'iso-transl
  (define-key iso-transl-ctl-x-8-map "\"" nil)
  (define-key iso-transl-ctl-x-8-map "'" nil)
  
  (define-key iso-transl-ctl-x-8-map "\"" "“")
  (define-key iso-transl-ctl-x-8-map "'" "‘"))

```

With the above snippet, C-x 8 ' will add a pair of curvy single quote and C-x 8 " will add a pair of curvy double quote.
