### ISSUE TITLE
the org-ox package cannot be used in Mac 10.15 (certificate problem?)

### ISSUE THREAD

**Issue by ouboub** [kjambunathan/org-mode-ox-odt#93]
Hi

I added the same setting to my GNU emacs (master) in MacOS.15
that is the package-archives variable is set to 
(("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
 ("melpa" . "http://melpa.org/packages/")
 ("ox-odt" . "https://kjambunathan.github.io/elpa"))

but when I run package-list-packages, I receive a strange error that I attach. Not sure who is the culprit here (I presume Mac 10.15 and its certificate politics) any advice would be very welcome
[add-rep.txt](https://github.com/kjambunathan/org-mode-ox-odt/files/6811885/add-rep.txt)

**Comment by kjambunathan** [comment]
> ("melpa" . "http://melpa.org/packages/")

> ("ox-odt" . "https://kjambunathan.github.io/elpa")

**You need a trailing slash after the elpa, much like what you have for other repos.**  You can see that every other package repo ends with trailing slash.  Nothing special with my elpa repo.    ELPA is basically a directory on the server that has `archive-contents` and related packages.  You can see the directory structure in my git repo https://github.com/kjambunathan/kjambunathan.github.io/tree/master/elpa


I am assuming that you are able to install from other archives like GNU ELPA and MELPA, and you are facing issues with my ELPA dir.   Otherwise it could be an issue with GnuTLS/LibreSSL and settingup of trustfiles. [This random issue](https://github.com/cask/cask/issues/418) touches on relative paths.


If you have trouble setting up GNU TLS, as a short-term workaround you  can clone my ELPA git repo, and subsequently do `M-x package-install-file` on the tar files you have downloaded.

 I believe setting up `package-archives` to `/tmp/kjambunathan.github.io/elpa/`--note the trailing backslash, it is important--and doing the usual dance with package refresh, marking and install will work as well.

```
$ cd /tmp
/tmp$ git clone --depth 1 https://github.com/kjambunathan/kjambunathan.github.io

Cloning into 'kjambunathan.github.io'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 0), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (7/7), 1.36 MiB | 1.03 MiB/s, done.

/tmp$ cd kjambunathan.github.io/

/tmp/kjambunathan.github.io$ ls

elpa  README.md
/tmp/kjambunathan.github.io$ cd elpa
/tmp/kjambunathan.github.io/elpa$ ls
archive-contents  JabrefExportChicagoODF-1.2.2.tar  ox-odt-9.3.7.323.tar
```

**Comment by ouboub** [comment]
oh, sorry, thanks very much, the missing /  solves the problem
